/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author filho
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textUsuario = new javax.swing.JTextField();
        textPass = new javax.swing.JPasswordField();
        jlbUsuario = new javax.swing.JLabel();
        jlbSemha = new javax.swing.JLabel();
        JlbLogin = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlbFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(textUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 180, 40));
        getContentPane().add(textPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 170, 50));

        jlbUsuario.setBackground(new java.awt.Color(0, 0, 0));
        jlbUsuario.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jlbUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jlbUsuario.setText("Usuario");
        getContentPane().add(jlbUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 110, 60));

        jlbSemha.setBackground(new java.awt.Color(0, 0, 0));
        jlbSemha.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jlbSemha.setForeground(new java.awt.Color(255, 255, 255));
        jlbSemha.setText("senha");
        getContentPane().add(jlbSemha, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 110, 60));

        JlbLogin.setBackground(new java.awt.Color(0, 0, 0));
        JlbLogin.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        JlbLogin.setForeground(new java.awt.Color(255, 255, 255));
        JlbLogin.setText("Login");
        getContentPane().add(JlbLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 110, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagem/barbeariaLogin2alterada.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 280, 490));

        jlbFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagem/logo imagem grande.jpg"))); // NOI18N
        jlbFundo.setText("jLabel1");
        getContentPane().add(jlbFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, -10, 570, 529));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JlbLogin;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jlbFundo;
    private javax.swing.JLabel jlbSemha;
    private javax.swing.JLabel jlbUsuario;
    private javax.swing.JPasswordField textPass;
    private javax.swing.JTextField textUsuario;
    // End of variables declaration//GEN-END:variables
}
